# Generated by Django 6.0.2 on 2026-04-04 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["is_published", "published_at"],
                name="core_blogpo_is_publ_9313b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["category", "is_published"],
                name="core_blogpo_categor_2d16db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["is_read", "created_at"], name="core_contac_is_read_f17b60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="faq",
            index=models.Index(
                fields=["category", "is_active"], name="core_faq_categor_181b73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testimonial",
            index=models.Index(
                fields=["is_active", "featured"], name="core_testim_is_acti_56b30b_idx"
            ),
        ),
    ]
