# Generated by Django 6.0.2 on 2026-02-24 09:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_tables', models.IntegerField(default=5)),
                ('max_records_per_table', models.IntegerField(default=1000)),
                ('max_team_members', models.IntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(default=list)),
                ('schema_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('record_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='dashboards.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=120)),
                ('layout_config', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='dashboards.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export'), ('share', 'Share')], max_length=20)),
                ('content_type', models.CharField(max_length=50)),
                ('object_id', models.UUIDField()),
                ('object_repr', models.CharField(max_length=200)),
                ('changes', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.workspace')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(related_name='workspaces', through='dashboards.WorkspaceMembership', through_fields=('workspace', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dashboards.datatable')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['table', 'is_active'], name='dashboards__table_i_0b9212_idx'), models.Index(fields=['table', 'updated_at'], name='dashboards__table_i_a85d28_idx'), models.Index(fields=['table', 'created_by'], name='dashboards__table_i_e06cf8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_type', models.CharField(choices=[('line_chart', 'Line Chart'), ('bar_chart', 'Bar Chart'), ('pie_chart', 'Pie Chart'), ('table', 'Data Table'), ('metric', 'Single Metric'), ('number', 'Number Card'), ('gauge', 'Gauge'), ('heatmap', 'Heatmap'), ('scatter', 'Scatter Plot')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('query_config', models.JSONField(default=dict)),
                ('viz_config', models.JSONField(default=dict)),
                ('position', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboards.dashboard')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboards.datatable')),
            ],
            options={
                'indexes': [models.Index(fields=['dashboard', 'widget_type'], name='dashboards__dashboa_25decc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='datatable',
            index=models.Index(fields=['workspace', 'is_active'], name='dashboards__workspa_2423f8_idx'),
        ),
        migrations.AddIndex(
            model_name='datatable',
            index=models.Index(fields=['workspace', 'updated_at'], name='dashboards__workspa_b7f001_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datatable',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['workspace', 'is_public'], name='dashboards__workspa_fd2961_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['public_uuid'], name='dashboards__public__3c2a88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboard',
            unique_together={('workspace', 'slug')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['workspace', 'timestamp'], name='dashboards__workspa_303c38_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='dashboards__user_id_f4f2d4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='dashboards__content_b31205_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['workspace', 'role'], name='dashboards__workspa_436d9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacemembership',
            unique_together={('workspace', 'user')},
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['owner', 'is_active'], name='dashboards__owner_i_e10033_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['tier'], name='dashboards__tier_dec9f5_idx'),
        ),
    ]
