# Generated by Django 6.0.3 on 2026-03-30 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workspace',
            name='dashboards__owner_i_e10033_idx',
        ),
        migrations.RemoveIndex(
            model_name='workspace',
            name='dashboards__tier_dec9f5_idx',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacemembership',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='workspacemembership',
            name='dashboards__workspa_436d9d_idx',
        ),
        migrations.AlterField(
            model_name='record',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.RemoveField(
            model_name='workspacemembership',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='workspacemembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workspacemembership',
            name='workspace',
        ),
        migrations.DeleteModel(
            name='Workspace',
        ),
        migrations.DeleteModel(
            name='WorkspaceMembership',
        ),
    ]
