# Generated by Django 6.0.2 on 2026-04-04 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0002_dashboard_deleted_at_importjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="record",
            index=models.Index(
                fields=["table", "is_active", "created_at"],
                name="rec_tbl_active_created_idx",
            ),
        ),
    ]
