# Generated by Django 6.0.2 on 2026-04-10 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0003_record_composite_index"),
        ("workspaces", "0004_workspace_onboarding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="file_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="importjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "running", "completed"])),
                fields=("table", "file_hash"),
                name="unique_successful_import_per_table_hash",
            ),
        ),
    ]
