# Generated by Django 6.0.2 on 2026-04-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0004_importjob_file_hash_idempotency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widget",
            name="position",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="widget",
            name="query_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="widget",
            name="viz_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
