# Generated by Django 6.0.2 on 2026-04-12 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0005_widget_blank_json_fields"),
        ("workspaces", "0004_workspace_onboarding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "field_name",
                    models.CharField(
                        help_text="Column in the DataTable to aggregate", max_length=100
                    ),
                ),
                (
                    "aggregate",
                    models.CharField(
                        choices=[
                            ("sum", "Sum"),
                            ("avg", "Average"),
                            ("count", "Count"),
                            ("min", "Minimum"),
                            ("max", "Maximum"),
                        ],
                        default="sum",
                        max_length=10,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("gt", "Greater than"),
                            ("gte", "Greater than or equal"),
                            ("lt", "Less than"),
                            ("lte", "Less than or equal"),
                            ("eq", "Equal to"),
                        ],
                        max_length=5,
                    ),
                ),
                ("threshold", models.FloatField()),
                ("is_active", models.BooleanField(default=True)),
                ("cooldown_minutes", models.PositiveIntegerField(default=60)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("last_value", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="dashboards.datatable",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "is_active"],
                        name="dashboards__workspa_8e4241_idx",
                    ),
                    models.Index(
                        fields=["table", "is_active"],
                        name="dashboards__table_i_b2df9e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("secret", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("total_requests", models.PositiveIntegerField(default=0)),
                ("last_request_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to="dashboards.datatable",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "is_active"],
                        name="dashboards__workspa_87dc58_idx",
                    )
                ],
            },
        ),
    ]
