# Generated by Django 6.0.2 on 2026-04-14 05:28
# Extended manually to include a data migration that encrypts existing
# plaintext secrets using Fernet (apps.dashboards.webhook_crypto).

from django.db import migrations, models


def encrypt_existing_secrets(apps, schema_editor):
    """Encrypt all existing plaintext secrets in place."""
    from apps.dashboards.webhook_crypto import encrypt_secret

    WebhookEndpoint = apps.get_model('dashboards', 'WebhookEndpoint')
    updated = 0
    for endpoint in WebhookEndpoint.objects.all():
        # A Fernet token always starts with 'gAAAAA' (base64-encoded bytes).
        # Skip rows that already look encrypted to make the migration idempotent.
        if endpoint.secret and not endpoint.secret.startswith('gAAAAA'):
            endpoint.secret = encrypt_secret(endpoint.secret)
            endpoint.save(update_fields=['secret'])
            updated += 1
    if updated:
        print(f"\n  Encrypted {updated} webhook secret(s).")


def noop_reverse(apps, schema_editor):
    # We intentionally do not decrypt on rollback — rolling back this migration
    # would leave the column narrower than the ciphertext length and the data
    # would be lost regardless.  Document this as a one-way migration.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0006_dataalert_webhookendpoint"),
    ]

    operations = [
        # 1. Widen the column first so ciphertext fits.
        migrations.AlterField(
            model_name="webhookendpoint",
            name="secret",
            field=models.CharField(max_length=256),
        ),
        # 2. Encrypt all existing plaintext values.
        migrations.RunPython(encrypt_existing_secrets, noop_reverse),
    ]
