# Generated by Django 6.0.2 on 2026-04-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0007_encrypt_webhook_secrets"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="filter_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
