# Generated by Django 6.0.2 on 2026-04-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0008_filter_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="import_mode",
            field=models.CharField(
                choices=[
                    ("replace", "Replace — overwrite all existing records"),
                    ("append", "Append — add rows without touching existing data"),
                    ("upsert", "Upsert — insert or update keyed on primary_key field"),
                ],
                default="append",
                help_text="How incoming rows are merged with existing data.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="primary_key_field",
            field=models.CharField(
                blank=True,
                help_text="Field name used as the unique key for upsert mode.",
                max_length=255,
            ),
        ),
    ]
