# Generated by Django 6.0.3 on 2026-04-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0009_import_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspaces", "__first__"),
    ]

    operations = [
        # ── DataSource model ─────────────────────────────────────────────────
        migrations.CreateModel(
            name="DataSource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("connector_type", models.CharField(
                    choices=[("postgresql", "PostgreSQL"), ("mysql", "MySQL")],
                    default="postgresql",
                    max_length=20,
                )),
                ("host", models.CharField(max_length=255)),
                ("port", models.PositiveIntegerField(default=5432)),
                ("database", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=200)),
                ("password_enc", models.TextField(blank=True, db_column="password_enc")),
                ("ssl_mode", models.CharField(
                    choices=[("disable", "Disable"), ("require", "Require"), ("verify-full", "Verify CA")],
                    default="require",
                    max_length=20,
                )),
                ("extra_options", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                ("last_test_ok", models.BooleanField(null=True)),
                ("last_test_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("workspace", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="data_sources",
                    to="workspaces.workspace",
                )),
                ("created_by", models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                "ordering": ["workspace", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(fields=["workspace", "is_active"], name="ds_ws_active_idx"),
        ),

        # ── Widget: data_source FK + source_table_name ───────────────────────
        migrations.AddField(
            model_name="widget",
            name="data_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="widgets",
                to="dashboards.datasource",
            ),
        ),
        migrations.AddField(
            model_name="widget",
            name="source_table_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
