# Generated by Django 6.0.3 on 2026-04-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0010_datasource_widget_connector"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datasource",
            old_name="password_enc",
            new_name="_password",
        ),
        migrations.RenameIndex(
            model_name="datasource",
            new_name="dashboards__workspa_ffcd6a_idx",
            old_name="ds_ws_active_idx",
        ),
    ]
