# Generated by Django 6.0.3 on 2026-04-17 12:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0013_calculatedfield"),
        ("workspaces", "0006_chat_integration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculatedfield",
            name="expression",
            field=models.TextField(
                help_text="Arithmetic expression. Use sum(col), count(col), avg(col), min(col), max(col) to aggregate column values. E.g.: sum(revenue) / count(user_id)",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="widget_type",
            field=models.CharField(
                choices=[
                    ("line_chart", "Line Chart"),
                    ("bar_chart", "Bar Chart"),
                    ("pie_chart", "Pie Chart"),
                    ("table", "Data Table"),
                    ("metric", "Single Metric"),
                    ("number", "Number Card"),
                    ("gauge", "Gauge"),
                    ("heatmap", "Heatmap"),
                    ("scatter", "Scatter Plot"),
                    ("cohort", "Cohort Retention"),
                    ("funnel", "Funnel Analysis"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ChatIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("slack", "Slack"), ("teams", "Microsoft Teams")],
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human label, e.g. '#alerts channel'", max_length=100
                    ),
                ),
                (
                    "webhook_url_enc",
                    models.TextField(
                        blank=True, help_text="Fernet-encrypted webhook URL"
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_integrations",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["provider"],
                "unique_together": {("workspace", "provider")},
            },
        ),
    ]
