# Generated by Django 6.0.3 on 2026-04-17 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0015_dashboard_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widget",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboards.datatable",
            ),
        ),
    ]
