# Generated by Django 6.0.3 on 2026-04-19 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0016_widget_table_cascade_delete"),
        ("workspaces", "0006_chat_integration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="datatable",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="datatable",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("workspace", "name"),
                name="unique_active_table_name_per_workspace",
            ),
        ),
    ]
