# Generated by Django 6.0.4 on 2026-04-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0018_alter_widget_widget_type_area_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('line_chart', 'Line Chart'), ('area_chart', 'Area Chart'), ('bar_chart', 'Bar Chart'), ('pie_chart', 'Pie Chart'), ('donut', 'Donut Chart'), ('histogram', 'Histogram'), ('box_plot', 'Box Plot'), ('scatter', 'Scatter Plot'), ('bubble', 'Bubble Chart'), ('waterfall', 'Waterfall Chart'), ('treemap', 'Treemap'), ('funnel_chart', 'Funnel Chart'), ('table', 'Data Table'), ('metric', 'Single Metric'), ('gauge', 'Gauge'), ('heatmap', 'Heatmap'), ('cohort', 'Cohort Retention'), ('funnel', 'Funnel Analysis')], max_length=20),
        ),
    ]
