# Generated by Django 6.0.2 on 2026-04-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_mpesatransaction"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stripewebhookevent",
            index=models.Index(
                fields=["processed", "event_type"],
                name="subscriptio_process_347a8f_idx",
            ),
        ),
    ]
