# Generated by Django 6.0.2 on 2026-04-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_stripewebhookevent_subscriptio_process_347a8f_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="dunning_stage",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscription",
            name="grace_period_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
