# Generated by Django 6.0.3 on 2026-04-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_grace_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpesatransaction",
            name="is_yearly",
            field=models.BooleanField(default=False),
        ),
    ]
