# Generated by Django 6.0.2 on 2026-04-04 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0002_workspaceinvitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="members",
            field=models.ManyToManyField(
                help_text="All users with access, including the owner.",
                related_name="workspaces",
                through="workspaces.WorkspaceMembership",
                through_fields=("workspace", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="owner",
            field=models.ForeignKey(
                help_text="The user who owns and administers this workspace.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_workspaces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
