# Generated by Django 6.0.3 on 2026-04-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0005_ssoconfiguration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ssoconfiguration",
            name="auto_provision",
            field=models.BooleanField(
                default=True,
                help_text="Automatically create a new AnalyticsMeta account for first-time SSO logins.  If disabled, the user must already have an account.",
            ),
        ),
        migrations.AlterField(
            model_name="ssoconfiguration",
            name="idp_slo_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="IdP SLO URL (optional, HTTP-Redirect binding)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="ssoconfiguration",
            name="idp_x509_cert",
            field=models.TextField(
                help_text="IdP X.509 certificate in PEM format. Remove the -----BEGIN/END CERTIFICATE----- headers — paste just the base64 body."
            ),
        ),
        migrations.AlterField(
            model_name="ssoconfiguration",
            name="is_active",
            field=models.BooleanField(
                default=False, help_text="Enable SSO login for this workspace."
            ),
        ),
        migrations.AlterField(
            model_name="ssoconfiguration",
            name="require_sso",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, workspace members may only sign in via SSO — password login is blocked for them.",
            ),
        ),
        migrations.AlterField(
            model_name="ssoconfiguration",
            name="sp_entity_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SP Entity ID. Leave blank to auto-generate from https://<host>/sso/<workspace_id>/metadata/",
                max_length=500,
            ),
        ),
    ]
