"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'channels',
    'daphne',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',

    # Allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.linkedin_oauth2',
    'rest_framework',

    # Local apps
    'apps.core',
    'apps.users',
    'apps.categories',
    'apps.charts',
    'apps.dashboards',
    'apps.exports',
    'apps.fields',
    'apps.formulas',
    'apps.imports',
    'apps.integrations',
    'apps.kpis',
    'apps.notifications',
    'apps.records',
    'apps.subscriptions',
    'apps.teams',
    'apps.templates_app',
    'apps.workspaces',
    'apps.newsletter',
    'apps.insights',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.dashboards.middleware.CurrentWorkspaceMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / '../templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.core.context_processors.site_settings',
                'apps.core.context_processors.navigation',
                'apps.newsletter.context_processors.newsletter_lists',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# ASGI configuration
ASGI_APPLICATION = 'config.asgi.application'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

SITE_ID = 1

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default Django auth
    'allauth.account.auth_backends.AuthenticationBackend',  # Allauth auth
]

# ============================================================================
# ACCOUNT CONFIGURATION (Local Authentication)
# ============================================================================

# Signup fields configuration (new in 65.x) [citation:1][citation:9]
ACCOUNT_SIGNUP_FIELDS = [
    'email*',      # Required
    'password1*',  # Required
    'password2*',  # Required
    # 'username*', # Uncomment if you want username field
]

# Login methods [citation:9]
ACCOUNT_LOGIN_METHODS = {'email'}  # Login with email only

# Email settings
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # "mandatory", "optional", or "none"
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_EMAIL_SUBJECT_PREFIX = "Business Sight Technologies - "

# Password settings
ACCOUNT_SIGNUP_PASSWORD_VERIFICATION = True  # Verify password confirmation
ACCOUNT_PASSWORD_MIN_LENGTH = 8  # Minimum password length
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = True  # Log out user after password change

# Login/Logout redirects
LOGIN_URL = "account_login"
LOGIN_REDIRECT_URL = "core:home"  # Redirect after login
LOGOUT_REDIRECT_URL = "core:home"  # Redirect after logout
ACCOUNT_LOGOUT_ON_GET = True  # Logout via GET request

# Advanced features
ACCOUNT_LOGIN_BY_CODE_ENABLED = True  # Magic link login [citation:9]
ACCOUNT_PASSKEY_LOGIN_ENABLED = True  # Passkey support

# Security
ACCOUNT_PREVENT_ENUMERATION = True  # Prevent account enumeration attacks
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m',  # 5 attempts per 5 minutes
    'signup': '5/5m',
}

# ============================================================================
# SOCIAL ACCOUNT CONFIGURATION
# ============================================================================

# Enable social authentication
SOCIALACCOUNT_ENABLED = True
SOCIALACCOUNT_ONLY = False  # Allow both local and social auth
SOCIALACCOUNT_AUTO_SIGNUP = True  # Auto signup with social account data 
SOCIALACCOUNT_STORE_TOKENS = True  # Store OAuth tokens
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True  # Authenticate by email match

# Social Account Providers Configuration [
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': config("GOOGLE_CLIENT_ID"),
            'secret': config("GOOGLE_CLIENT_SECRET"),
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'METHOD': 'oauth2',
        'VERIFIED_EMAIL': True,  # Treat email as verified if provider says so
        'EMAIL_AUTHENTICATION': True,  # Auto-connect if email matches
    },
    "openid_connect": {
        "APPS": [
            {
                "provider_id": "linkedin",
                "name": "LinkedIn",
                "client_id": config("LINKEDIN_CLIENT_ID"),
                "secret": config("LINKEDIN_CLIENT_SECRET"),
                "settings": {
                    "server_url": "https://www.linkedin.com/oauth",
                },
            }
        ]
    }
    
}

# Sending email settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config("EMAIL_HOST_USER")  # Your email address
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")  # Your email password


SUPPORT_EMAIL = config('SUPPORT_EMAIL', default='support@businessight.com')
SALES_EMAIL = config('SALES_EMAIL', default='sales@businessight.com')
PHONE_NUMBER = config('PHONE_NUMBER', default='+254 798 393 182')
ADDRESS = config('ADDRESS', default='123 Analytics Ave, Nairobi, CA 94105')
SITE_NAME = config('SITE_NAME', default='Businessight')
SITE_URL = config('SITE_URL', default='http://localhost:8000')

# Newsletter Settings
NEWSLETTER_CONFIRM_REDIRECT = '/'  # Where to redirect after confirmation
DISPOSABLE_EMAIL_DOMAINS = ['tempmail.com', 'throwaway.com']  # Optional

# Redis Configuration - Use environment variables for flexibility
REDIS_URL = config('REDIS_URL', 'redis://localhost:6379/0')
REDIS_HOST = config('REDIS_HOST', 'localhost')
REDIS_PORT = int(config('REDIS_PORT', 6379))
REDIS_DB = int(config('REDIS_DB', 0))

# Cache settings (for tracking pixels)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_URL,
        'KEY_PREFIX': 'analyticsmeta',
        'TIMEOUT': 300,  # 5 minutes default timeout
    }
}

# Add a second cache for session storage if needed
CACHES['sessions'] = {
    'BACKEND': 'django.core.cache.backends.redis.RedisCache',
    'LOCATION': f'{REDIS_URL}/1',
    'KEY_PREFIX': 'sessions',
}

# Celery Configuration
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600,
    'socket_connect_timeout': 10,
    'socket_timeout': 10,
}

# Channel layers (using Redis)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
            "capacity": 1500,  # Default capacity
            "expiry": 10,  # Default expiry
        },
    },
}

# Rate limiting (requires django-ratelimit)
RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = 'default'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/hour'
    }
}

# Session configuration - use Redis for sessions in production
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'sessions'