"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'channels',
    'daphne',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',

    # Allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.linkedin_oauth2',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',

    # Local apps
    'apps.core',
    'apps.users',
    'apps.dashboards',
    'apps.exports',
    'apps.notifications',
    'apps.subscriptions',
    'apps.workspaces',
    'apps.newsletter',
    'apps.insights',
    'apps.reports',
]

MIDDLEWARE = [
    # Must be first — starts request timer for Prometheus latency histograms
    'apps.core.middleware.PrometheusMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.dashboards.middleware.CurrentWorkspaceMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / '../templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.core.context_processors.site_settings',
                'apps.core.context_processors.navigation',
                'apps.newsletter.context_processors.newsletter_lists',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# ASGI configuration
ASGI_APPLICATION = 'config.asgi.application'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

SITE_ID = 1

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# SECURITY HARDENING
# ============================================================================

X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True

# Upload limits — prevent DoS via oversized uploads
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Session hardening
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 1_209_600  # 2 weeks in seconds

# CSRF hardening
CSRF_COOKIE_HTTPONLY = False    # Must be False for JS CSRF tokens to work
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False       # Cookie-based (default)

# ---------------------------------------------------------------------------
# M-Pesa Daraja API (Safaricom)
# Defaults below are Safaricom's PUBLIC sandbox test credentials — safe for
# development only.  production.py overrides all of these with no defaults,
# so missing env vars will raise an error at startup in production.
# ---------------------------------------------------------------------------
MPESA_SANDBOX = config('MPESA_SANDBOX', default=True, cast=bool)
MPESA_CONSUMER_KEY = config('MPESA_CONSUMER_KEY', default='')
MPESA_CONSUMER_SECRET = config('MPESA_CONSUMER_SECRET', default='')
# Safaricom public sandbox shortcode and passkey for Lipa Na M-Pesa Online
MPESA_SHORTCODE = config('MPESA_SHORTCODE', default='174379')
MPESA_PASSKEY = config(
    'MPESA_PASSKEY',
    default='bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919',
)
# In sandbox: set this to your ngrok/tunnel URL so callbacks reach your machine.
# In production: production.py requires this to be set explicitly via env var.
MPESA_CALLBACK_URL = config(
    'MPESA_CALLBACK_URL',
    default='https://sandbox.safaricom.co.ke/mpesa/callback/',
)

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default Django auth
    'allauth.account.auth_backends.AuthenticationBackend',  # Allauth auth
]

# ============================================================================
# ACCOUNT CONFIGURATION (Local Authentication)
# ============================================================================

# Signup fields configuration (new in 65.x) [citation:1][citation:9]
ACCOUNT_SIGNUP_FIELDS = [
    'email*',      # Required
    'password1*',  # Required
    'password2*',  # Required
    # 'username*', # Uncomment if you want username field
]

# Login methods [citation:9]
ACCOUNT_LOGIN_METHODS = {'email'}  # Login with email only

# Email settings
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # "mandatory", "optional", or "none"
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_EMAIL_SUBJECT_PREFIX = "Business Sight Technologies - "

# Password settings
ACCOUNT_SIGNUP_PASSWORD_VERIFICATION = True  # Verify password confirmation
ACCOUNT_PASSWORD_MIN_LENGTH = 8  # Minimum password length
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = True  # Log out user after password change

# Login/Logout redirects
LOGIN_URL = "account_login"
LOGIN_REDIRECT_URL = "/dashboard/analytics/"  # Redirect after login to dashboard
LOGOUT_REDIRECT_URL = "/"  # Redirect after logout to home
ACCOUNT_LOGOUT_ON_GET = False  # POST required to prevent CSRF-triggered logouts

# Advanced features
ACCOUNT_LOGIN_BY_CODE_ENABLED = True  # Magic link login [citation:9]
ACCOUNT_PASSKEY_LOGIN_ENABLED = True  # Passkey support

# Security
ACCOUNT_PREVENT_ENUMERATION = True  # Prevent account enumeration attacks
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m',  # 5 attempts per 5 minutes
    'signup': '5/5m',
}

# ============================================================================
# SOCIAL ACCOUNT CONFIGURATION
# ============================================================================

# Enable social authentication
SOCIALACCOUNT_ENABLED = True
SOCIALACCOUNT_ONLY = False  # Allow both local and social auth
SOCIALACCOUNT_AUTO_SIGNUP = True  # Auto signup with social account data 
SOCIALACCOUNT_STORE_TOKENS = True  # Store OAuth tokens
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True  # Authenticate by email match

# Social Account Providers Configuration [
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': config("GOOGLE_CLIENT_ID"),
            'secret': config("GOOGLE_CLIENT_SECRET"),
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'METHOD': 'oauth2',
        'VERIFIED_EMAIL': True,  # Treat email as verified if provider says so
        'EMAIL_AUTHENTICATION': True,  # Auto-connect if email matches
    },
    "openid_connect": {
        "APPS": [
            {
                "provider_id": "linkedin",
                "name": "LinkedIn",
                "client_id": config("LINKEDIN_CLIENT_ID"),
                "secret": config("LINKEDIN_CLIENT_SECRET"),
                "settings": {
                    "server_url": "https://www.linkedin.com/oauth",
                },
            }
        ]
    }
    
}

# Sending email settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config("EMAIL_HOST_USER")  # Your email address
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")  # Your email password
DEFAULT_FROM_EMAIL = config("EMAIL_HOST_USER")  # Must match the authenticated Gmail account


SUPPORT_EMAIL = config('SUPPORT_EMAIL', default='support@businessight.com')
SALES_EMAIL = config('SALES_EMAIL', default='sales@businessight.com')
PHONE_NUMBER = config('PHONE_NUMBER', default='+254 798 393 182')
ADDRESS = config('ADDRESS', default='123 Analytics Ave, Nairobi, CA 94105')
SITE_NAME = config('SITE_NAME', default='Businessight')
SITE_URL = config('SITE_URL', default='http://localhost:8000')

# Newsletter Settings
NEWSLETTER_CONFIRM_REDIRECT = '/'  # Where to redirect after confirmation
DISPOSABLE_EMAIL_DOMAINS = ['tempmail.com', 'throwaway.com']  # Optional

# Redis Configuration - Use environment variables for flexibility
REDIS_URL = config('REDIS_URL', 'redis://localhost:6379/0')
REDIS_HOST = config('REDIS_HOST', 'localhost')
REDIS_PORT = int(config('REDIS_PORT', 6379))
REDIS_DB = int(config('REDIS_DB', 0))

# Cache settings (for tracking pixels)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_URL,
        'KEY_PREFIX': 'analyticsmeta',
        'TIMEOUT': 300,  # 5 minutes default timeout
    }
}

# Session cache — uses same Redis DB but isolated via KEY_PREFIX.
# Upstash free tier only provides a single DB (0), so we rely on the prefix.
CACHES['sessions'] = {
    'BACKEND': 'django.core.cache.backends.redis.RedisCache',
    'LOCATION': REDIS_URL,
    'KEY_PREFIX': 'sessions',
    'TIMEOUT': SESSION_COOKIE_AGE,
}

# Celery Configuration
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600,
    'socket_connect_timeout': 10,
    'socket_timeout': 10,
}

# ── Celery Beat Schedule ────────────────────────────────────────────────────
from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE = {
    # Purge AuditLog rows older than AUDIT_LOG_RETENTION_DAYS (default 90 days)
    # Runs daily at 02:30 UTC to avoid peak hours.
    'prune-audit-logs-daily': {
        'task':     'dashboards.prune_audit_logs',
        'schedule': crontab(hour=2, minute=30),
    },
    # Evaluate DataAlerts every 15 minutes
    'check-data-alerts': {
        'task':     'dashboards.check_data_alerts',
        'schedule': crontab(minute='*/15'),
    },
    # Advance dunning sequence for past_due subscriptions and downgrade
    # workspaces whose grace period has expired. Runs daily at 08:00 UTC so
    # owners receive reminder emails at a reasonable hour.
    'process-grace-periods-daily': {
        'task':     'subscriptions.process_grace_periods',
        'schedule': crontab(hour=8, minute=0),
    },
    # Evaluate ReportSchedule records and fire delivery for any that are due.
    # Runs every 15 minutes — max schedule latency is therefore 15 minutes.
    'process-report-schedules': {
        'task':     'apps.reports.tasks.process_report_schedules',
        'schedule': crontab(minute='*/15'),
    },
    # Run statistical anomaly detection across all active workspaces.
    # Fires daily at 03:00 UTC — results are ready before the working day starts.
    'auto-anomaly-detection-daily': {
        'task':     'insights.auto_trigger_anomaly_detection',
        'schedule': crontab(hour=3, minute=0),
    },
}

# Retention days for AuditLog (overridable per-environment)
AUDIT_LOG_RETENTION_DAYS = config('AUDIT_LOG_RETENTION_DAYS', default=90, cast=int)

# Channel layers (using Redis)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
            "capacity": 1500,  # Default capacity
            "expiry": 10,  # Default expiry
        },
    },
}

# Rate limiting (requires django-ratelimit)
RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = 'default'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/hour',
        # Custom scopes defined in api_v1.py
        'registration': '10/hour',   # account creation — strict to block mass sign-ups
        'file_upload': '30/hour',    # import jobs per authenticated user
    }
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'AnalyticsMeta API',
    'DESCRIPTION': (
        'REST API for AnalyticsMeta — a multi-tenant BI SaaS platform. '
        'All endpoints require Token authentication unless noted.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
        'displayRequestDuration': True,
    },
}

# ── Stripe ──────────────────────────────────────────────────────────────────
# All three default to '' so development works without Stripe keys.
# In production, set real values via environment variables.
# STRIPE_WEBHOOK_SECRET is required for signature verification — if left
# empty the webhook handler will log a warning and skip verification (dev only).
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY', default='')
STRIPE_SECRET_KEY      = config('STRIPE_SECRET_KEY',      default='')
STRIPE_WEBHOOK_SECRET  = config('STRIPE_WEBHOOK_SECRET',  default='')

# Session configuration - use Redis for sessions in production
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'sessions'

# ============================================================================
# QUERY ENGINE TUNING
# These values are read by apps/dashboards/services.py — adjust to match your
# hardware and expected workspace sizes.
# ============================================================================
# Maximum records pulled into Python memory for JSON-field aggregations
QUERY_ENGINE_MAX_RECORDS = int(config('QUERY_ENGINE_MAX_RECORDS', default=10000))
# Number of records loaded when profiling / auto-detecting schema
QUERY_ENGINE_PROFILE_SAMPLE = int(config('QUERY_ENGINE_PROFILE_SAMPLE', default=1000))
# Batch size for bulk_create during CSV/Excel import
IMPORT_BATCH_SIZE = int(config('IMPORT_BATCH_SIZE', default=200))
# How long (seconds) widget query results are cached in Redis
WIDGET_CACHE_TTL = int(config('WIDGET_CACHE_TTL', default=300))
# Maximum file size (bytes) accepted by the import endpoint — default 50 MB
MAX_IMPORT_FILE_BYTES = int(config('MAX_IMPORT_FILE_BYTES', default=50 * 1024 * 1024))
# Django core upload limits — prevents request body DOS before Django processes the file
FILE_UPLOAD_MAX_MEMORY_SIZE = MAX_IMPORT_FILE_BYTES   # files above this go to temp disk
DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_IMPORT_FILE_BYTES   # max request body size

# ============================================================================
# LLM / AI SETTINGS
# ============================================================================
# Anthropic API key — required for LLM-enhanced insights (optional feature)
ANTHROPIC_API_KEY = config('ANTHROPIC_API_KEY', default='')
# Claude model to use for insight narratives
CLAUDE_INSIGHT_MODEL = config('CLAUDE_INSIGHT_MODEL', default='claude-sonnet-4-6')
# Monthly token budget per workspace (input + output combined).
# Set to 0 to disable LLM insights entirely.
LLM_WORKSPACE_MONTHLY_TOKEN_BUDGET = int(
    config('LLM_WORKSPACE_MONTHLY_TOKEN_BUDGET', default=100_000)
)

# ============================================================================
# WEBSOCKET / CHANNELS TUNING
# ============================================================================
# Sliding-window rate limit for WebSocket messages per connection
WS_RATE_LIMIT_WINDOW   = int(config('WS_RATE_LIMIT_WINDOW',   default=10))   # seconds
WS_RATE_LIMIT_MAX_MSGS = int(config('WS_RATE_LIMIT_MAX_MSGS', default=30))   # per window
# Idle timeout — server closes connection after this many seconds with no ping
WS_HEARTBEAT_TIMEOUT   = int(config('WS_HEARTBEAT_TIMEOUT',   default=90))   # seconds
# Max simultaneous WebSocket connections per authenticated user (all consumer types combined)
WS_MAX_CONNECTIONS_PER_USER = int(config('WS_MAX_CONNECTIONS_PER_USER', default=10))

# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# ── Structlog — structured JSON logging ────────────────────────────────────
import structlog  # noqa: E402

structlog.configure(
    processors=[
        structlog.stdlib.filter_by_level,
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.TimeStamper(fmt='iso'),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.UnicodeDecoder(),
        structlog.processors.JSONRenderer(),
    ],
    context_class=dict,
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)

# ── Sentry — error tracking (opt-in via SENTRY_DSN env var) ───────────────
SENTRY_DSN = config('SENTRY_DSN', default='')

if SENTRY_DSN:
    import sentry_sdk  # noqa: E402
    from sentry_sdk.integrations.django import DjangoIntegration  # noqa: E402
    from sentry_sdk.integrations.celery import CeleryIntegration  # noqa: E402
    from sentry_sdk.integrations.redis import RedisIntegration    # noqa: E402
    from sentry_sdk.integrations.logging import LoggingIntegration # noqa: E402
    import logging as _logging  # noqa: E402

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(
                transaction_style='url',
                http_methods_to_capture=('GET', 'POST', 'PUT', 'PATCH', 'DELETE'),
            ),
            CeleryIntegration(monitor_beat_tasks=True),
            RedisIntegration(),
            LoggingIntegration(
                level=_logging.INFO,        # breadcrumbs from INFO+
                event_level=_logging.ERROR, # errors from ERROR+ only
            ),
        ],
        # Capture 5% of transactions for performance monitoring (adjust in prod)
        traces_sample_rate=config('SENTRY_TRACES_SAMPLE_RATE', default=0.05, cast=float),
        # Release tag — populated by CI via GIT_COMMIT env var
        release=config('GIT_COMMIT', default=None),
        environment=config('DJANGO_ENV', default='development'),
        send_default_pii=False,  # GDPR: do not send user IP / email to Sentry
    )

# ── Prometheus ─────────────────────────────────────────────────────────────
# Custom PrometheusMiddleware in apps.core.middleware instruments HTTP requests.
# Celery task metrics are wired via signal handlers in apps.core.metrics.
# The /metrics endpoint is served by apps.core.views.metrics_view.
# ── SAML 2.0 SP credentials ────────────────────────────────────────────────
# Optional: provide a self-signed or CA-issued certificate + private key for
# signing AuthnRequests and SP metadata.  Leave blank for development; the
# IdP will not require request signing in most dev setups.
#
# In production, generate with:
#   openssl req -x509 -newkey rsa:2048 -keyout saml.key -out saml.crt \
#       -days 3650 -nodes -subj "/CN=analyticsmeta-sp"
# Then set SAML_SP_CERT / SAML_SP_KEY in your .env to the base64 body
# (without PEM headers) of saml.crt / saml.key respectively.
SAML_SP_CERT = config('SAML_SP_CERT', default='')
SAML_SP_KEY  = config('SAML_SP_KEY',  default='')
