# Generated by Django 6.0.2 on 2026-02-18 14:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('content_html', models.TextField()),
                ('content_text', models.TextField(blank=True)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('require_double_optin', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('preheader', models.CharField(blank=True, help_text='Preview text shown after subject line', max_length=255)),
                ('content_html', models.TextField(help_text='HTML email content')),
                ('content_text', models.TextField(blank=True, help_text='Plain text version (auto-generated if empty)')),
                ('segments', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_ab_test', models.BooleanField(default=False)),
                ('ab_test_variants', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('total_sent', models.PositiveIntegerField(default=0)),
                ('total_opens', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('total_bounces', models.PositiveIntegerField(default=0)),
                ('total_unsubscribes', models.PositiveIntegerField(default=0)),
                ('track_opens', models.BooleanField(default=True)),
                ('track_clicks', models.BooleanField(default=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('from_email', models.EmailField(default='webmaster@localhost', max_length=254)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ab_test_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ab_test_variants_set', to='newsletter.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('lists', models.ManyToManyField(related_name='campaigns', to='newsletter.list')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text="Subscriber's email address", max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Confirmation'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained')], db_index=True, default='pending', max_length=20)),
                ('source', models.CharField(choices=[('website', 'Website Footer'), ('landing', 'Landing Page'), ('import', 'Bulk Import'), ('api', 'API'), ('referral', 'Referral')], default='website', max_length=20)),
                ('total_opens', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('last_opened', models.DateTimeField(blank=True, null=True)),
                ('last_clicked', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('subscribed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['email', 'status'], name='newsletter__email_4db305_idx'), models.Index(fields=['unsubscribe_token'], name='newsletter__unsubsc_cc7505_idx'), models.Index(fields=['-subscribed_at'], name='newsletter__subscri_5714da_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.list')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.subscriber')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='subscribers',
            field=models.ManyToManyField(related_name='lists', through='newsletter.ListSubscription', to='newsletter.subscriber'),
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('unsubscribed', 'Unsubscribed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('clicked_links', models.JSONField(blank=True, default=list)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='newsletter.campaign')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_recipients', to='newsletter.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='BounceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bounce_type', models.CharField(choices=[('hard', 'Hard Bounce'), ('soft', 'Soft Bounce'), ('complaint', 'Complaint')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.campaign')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounce_reports', to='newsletter.subscriber')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'event_type', 'processed'], name='newsletter__provide_62ac80_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('url_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='newsletter.campaign')),
            ],
            options={
                'indexes': [models.Index(fields=['url_hash'], name='newsletter__url_has_415933_idx'), models.Index(fields=['campaign', '-click_count'], name='newsletter__campaig_c56e3e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'scheduled_for'], name='newsletter__status_590675_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['-created_at'], name='newsletter__created_2d0788_idx'),
        ),
        migrations.AddIndex(
            model_name='listsubscription',
            index=models.Index(fields=['subscriber', 'list', 'subscribed_at'], name='newsletter__subscri_4952c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listsubscription',
            unique_together={('subscriber', 'list')},
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'status'], name='newsletter__campaig_da95e7_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['message_id'], name='newsletter__message_c19b3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignrecipient',
            unique_together={('campaign', 'subscriber')},
        ),
        migrations.AddIndex(
            model_name='bouncereport',
            index=models.Index(fields=['subscriber', '-created_at'], name='newsletter__subscri_1a102b_idx'),
        ),
    ]
