# Generated by Django 6.0.2 on 2026-04-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="clicklink",
            name="newsletter__url_has_415933_idx",
        ),
        migrations.AlterField(
            model_name="campaign",
            name="from_email",
            field=models.EmailField(default="sniphermarube@gmail.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="clicklink",
            name="url_hash",
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="clicklink",
            unique_together={("campaign", "url_hash")},
        ),
        migrations.AddIndex(
            model_name="clicklink",
            index=models.Index(
                fields=["campaign", "url_hash"], name="newsletter__campaig_37d474_idx"
            ),
        ),
    ]
