# Generated by Django 6.0.4 on 2026-04-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_fix_clicklink_url_hash_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='from_email',
            field=models.EmailField(default='linetawino2018@gmail.com', max_length=254),
        ),
    ]
