import uuid
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models import JSONField
from apps.workspaces.models import Workspace

User = get_user_model()


class Insight(models.Model):
    """
    AI-generated insight for a workspace – a single finding with optional chart data.
    """
    INSIGHT_TYPES = [
        ('trend', 'Trend'),
        ('anomaly', 'Anomaly'),
        ('summary', 'Summary'),
        ('prediction', 'Prediction'),
        ('comparison', 'Comparison'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    workspace = models.ForeignKey(Workspace, on_delete=models.CASCADE, related_name='insights')

    title = models.CharField(max_length=200)
    description = models.TextField()
    insight_type = models.CharField(max_length=20, choices=INSIGHT_TYPES, default='summary')

    # Optional chart data for rendering
    chart_data = JSONField(default=dict, blank=True)

    # Link back to the source table, if applicable
    source_table_name = models.CharField(max_length=100, blank=True)

    # LLM provenance — populated when the insight narrative was generated by Claude
    llm_model         = models.CharField(max_length=80, blank=True)
    prompt_tokens     = models.PositiveIntegerField(default=0)
    completion_tokens = models.PositiveIntegerField(default=0)

    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['workspace', 'insight_type']),
            models.Index(fields=['workspace', 'created_at']),
        ]

    def __str__(self):
        return f"{self.title} ({self.workspace.name})"


class WorkspaceLLMBudget(models.Model):
    """
    Monthly token budget tracker for LLM-powered insights per workspace.

    Reset cadence: a new row is inserted each calendar month.  The task
    checks ``tokens_used < monthly_limit`` before calling the Claude API.
    Setting ``monthly_limit = 0`` disables LLM insights for the workspace.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    workspace = models.ForeignKey(
        Workspace, on_delete=models.CASCADE, related_name='llm_budgets'
    )
    # Calendar month this row tracks — stored as YYYY-MM-01 for easy grouping
    month = models.DateField()
    tokens_used = models.PositiveBigIntegerField(default=0)
    monthly_limit = models.PositiveBigIntegerField(
        help_text='Maximum combined input+output tokens this workspace may use in the month. '
                  '0 = disabled.'
    )

    class Meta:
        unique_together = ('workspace', 'month')
        indexes = [models.Index(fields=['workspace', 'month'])]

    def __str__(self):
        return f"LLMBudget({self.workspace.name}, {self.month}, {self.tokens_used}/{self.monthly_limit})"

    def has_capacity(self, estimated_tokens: int = 0) -> bool:
        """Return True if the budget allows at least *estimated_tokens* more tokens."""
        if self.monthly_limit == 0:
            return False
        return (self.tokens_used + estimated_tokens) <= self.monthly_limit

    def consume(self, tokens: int) -> None:
        """Atomically increment tokens_used. Safe for concurrent Celery calls."""
        WorkspaceLLMBudget.objects.filter(pk=self.pk).update(
            tokens_used=models.F('tokens_used') + tokens
        )
