# Generated by Django 6.0.2 on 2026-04-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="reportjob",
            new_name="reports_rep_workspa_04598c_idx",
            old_name="rpt_ws_dash_status_idx",
        ),
        migrations.RenameIndex(
            model_name="reportjob",
            new_name="reports_rep_share_t_bdeab9_idx",
            old_name="rpt_share_token_idx",
        ),
    ]
