# Generated by Django 6.0.2 on 2026-04-14 05:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reports",
            "0002_rename_rpt_ws_dash_status_idx_reports_rep_workspa_04598c_idx_and_more",
        ),
        ("workspaces", "0004_workspace_onboarding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dashboard_id", models.UUIDField()),
                ("name", models.CharField(max_length=200)),
                (
                    "cron_expression",
                    models.CharField(
                        default="0 8 * * 1",
                        help_text='Cron expression (UTC). E.g. "0 8 * * 1" = Mon 08:00.',
                        max_length=100,
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        default=list,
                        help_text="List of email addresses to deliver the report to.",
                    ),
                ),
                (
                    "report_format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("csv", "CSV")],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_send_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Pre-computed next fire time (UTC). Updated after each send.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_schedules",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["workspace", "name"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "is_active", "next_send_at"],
                        name="reports_rep_workspa_c786df_idx",
                    )
                ],
            },
        ),
    ]
