# Generated by Django 6.0.2 on 2026-03-31 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0002_workspaceinvitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("trend", "Trend"),
                            ("anomaly", "Anomaly"),
                            ("summary", "Summary"),
                            ("prediction", "Prediction"),
                            ("comparison", "Comparison"),
                        ],
                        default="summary",
                        max_length=20,
                    ),
                ),
                ("chart_data", models.JSONField(blank=True, default=dict)),
                ("source_table_name", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "insight_type"],
                        name="insights_in_workspa_469194_idx",
                    ),
                    models.Index(
                        fields=["workspace", "created_at"],
                        name="insights_in_workspa_2e31a1_idx",
                    ),
                ],
            },
        ),
    ]
