# Generated by Django 6.0.2 on 2026-04-11 07:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0001_initial"),
        ("workspaces", "0004_workspace_onboarding"),
    ]

    operations = [
        migrations.AddField(
            model_name="insight",
            name="completion_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="insight",
            name="llm_model",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="insight",
            name="prompt_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="WorkspaceLLMBudget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("month", models.DateField()),
                ("tokens_used", models.PositiveBigIntegerField(default=0)),
                (
                    "monthly_limit",
                    models.PositiveBigIntegerField(
                        help_text="Maximum combined input+output tokens this workspace may use in the month. 0 = disabled."
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_budgets",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["workspace", "month"],
                        name="insights_wo_workspa_800f0c_idx",
                    )
                ],
                "unique_together": {("workspace", "month")},
            },
        ),
    ]
