# Generated by Django 6.0.4 on 2026-04-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_agentic_ai_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='insight',
            new_name='insights_in_session_2b2f21_idx',
            old_name='insights_session_id_idx',
        ),
        migrations.AlterField(
            model_name='insight',
            name='insight_type',
            field=models.CharField(choices=[('trend', 'Trend'), ('anomaly', 'Anomaly'), ('summary', 'Summary'), ('prediction', 'Prediction'), ('comparison', 'Comparison'), ('ask_ai', 'Ask AI'), ('viz_suggestion', 'Visualization Suggestion')], default='summary', max_length=20),
        ),
    ]
