# Generated by Django 6.0.3 on 2026-04-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="whatsapp_alerts",
            field=models.BooleanField(
                default=False, help_text="Send data-alert notifications via WhatsApp"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                help_text="E.164 format, e.g. +254712345678. Leave blank to disable WhatsApp alerts.",
                max_length=20,
            ),
        ),
    ]
